// Data Object for Products (Scalability and inventory tracking)
const data = {
  products: [
    {
      _id: '1',
      name: 'Whistle Zipper Pull',
      // Slug is what you see on the URL
      slug: 'Whistle-Zipper-Pull',
      category: 'Zipper Pulls',
      image: '/images/1_Cor_Zip.jpg', // All images are 679px x 829px, created in rems for responsive design
      price: 5,
      countInStock: 2,
      rating: 0,
      numReviews: 0,
      description: 'Zipper pull with silver whistle and biblical charm',
    },
    {
      _id: '2',
      name: 'Pink and Grey Macrame Keychain',
      slug: 'PG_Mac_Keychain',
      category: 'Keychains',
      image: '/images/Beaded_Mac_Key.jpg',
      price: 7,
      countInStock: 1,
      rating: 0,
      numReviews: 0,
      description: 'Pink and gray zig-zag beaded keychain',
    },
    {
      _id: '3',
      name: 'Ballerina Floral Simple Burping Cloth (Girl)',
      slug: 'BF_Burping_Cloth_Girl',
      category: 'Burping Cloths',
      image: '/images/Burp_Girl_Set_1.jpg',
      price: 10,
      countInStock: 1,
      rating: 0,
      numReviews: 0,
      description: 'Ballerina print burping cloths made from cloth diapers',
    },
    {
      _id: '4',
      name: 'Floral Simple Burping Cloth (Girl)',
      slug: 'F_Simple_Burping_Cloth',
      category: 'Burp Cloths',
      image: '/images/Burp_Girl_Set_2.jpg',
      price: 10,
      countInStock: 1,
      rating: 0,
      numReviews: 0,
      description: 'Floral print burping cloths made from cloth diapers',
    },
    {
      _id: '5',
      name: 'Music Speaks Guitar Pick Necklace (Silver)',
      slug: 'Music_Speaks_Guitar_Pick_Neck',
      category: 'Necklaces',
      image: '/images/Guitar_Pick_Neck.jpg',
      price: 8,
      countInStock: 2,
      rating: 0,
      numReviews: 0,
      description: 'Guitar Pick Shaped Necklace',
    },
    {
      _id: '6',
      name: 'Black QRS Complex Bracelet (Heartbeat Line)',
      slug: 'QRS_Bracelet_HBL_Black',
      category: 'Bracelets',
      image: '/images/Heartbeat_Black.jpg',
      price: 6,
      countInStock: 1,
      rating: 0,
      numReviews: 0,
      description: 'QRS Complex on a black leather bracelet',
    },
    {
      _id: '7',
      name: 'Gray QRS Complex Bracelet (Heartbeat Line)',
      slug: 'QRS_Complex_HBL_Gray',
      category: 'Bracelets',
      image: '/images/Heartbeat_Gray.jpg',
      price: 6,
      countInStock: 1,
      rating: 0,
      numReviews: 0,
      description: 'QRS Complex on a gray leather bracelet',
    },
    {
      _id: '8',
      name: 'Quilted Ironing Board Cover',
      slug: 'Quilted_Ironing_Board_Cover',
      category: 'Home Goods',
      image: '/images/Ironboard_Cov.jpg',
      price: 12,
      countInStock: 1,
      rating: 0,
      numReviews: 0,
      description:
        'Mauve and floral quilted ironing board cover with drawstring closure',
    },
    {
      _id: '9',
      name: 'Light to Dark Faded Jade Colored Earrings',
      slug: 'LtD_Faded_Jade_Colored_Ear',
      category: 'Earrings',
      image: '/images/Jade_Ear.jpg',
      price: 6,
      countInStock: 2,
      rating: 0,
      numReviews: 0,
      description: 'Light to dark fade jade colored earrings',
    },
    {
      _id: '10',
      name: 'Patriotic Yellow Ribbon Zipper Pull',
      slug: 'Pat_Yellow_Rib_Zip_Pull',
      category: 'Zipper Pulls',
      image: '/images/Patriot_Zip.jpg',
      price: 8,
      countInStock: 2,
      rating: 0,
      numReviews: 0,
      description: 'Patriotic yellow ribbon themed zipper pull',
    },
    {
      _id: '11',
      name: 'Potato Bag Vintage Bird Print',
      slug: 'Pot_Bag_Vin_Bird_Print',
      category: 'Home Goods',
      image: '/images/Pot_Birds_Bag.jpg',
      price: 10,
      countInStock: 1,
      rating: 0,
      numReviews: 0,
      description:
        'Pink and plaid vintage bird print potato bag (includes instructions)',
    },
    {
      _id: '12',
      name: 'Potato Bag Black Velvet Print',
      slug: 'Pot_Bag_Black_Velvet_Print',
      category: 'Home Goods',
      image: '/images/Pot_Black_Bag.jpg',
      price: 10,
      countInStock: 1,
      rating: 0,
      numReviews: 0,
      description: 'Black velvet print potato bag (includes instructions)',
    },
    {
      _id: '13',
      name: 'Potato Bag Red Floral Print',
      slug: 'Pot_Bag_Red_Floral_Print',
      category: 'Home Goods',
      image: '/images/Pot_Floral_Bag.jpg',
      price: 10,
      countInStock: 1,
      rating: 0,
      numReviews: 0,
      description: 'Red floral print potato bag (includes instructions)',
    },
    {
      _id: '14',
      name: 'Potato Bag Black with White Paw Print',
      slug: 'Pot_Bag_Black_White_Paws_Print',
      category: 'Home Goods',
      image: '/images/Pot_Paws_Bag.jpg',
      price: 10,
      countInStock: 1,
      rating: 0,
      numReviews: 0,
      description:
        'Black and white paw print potato bag (includes instructions)',
    },
    {
      _id: '15',
      name: 'Potato Bag Pink Dot Print',
      slug: 'Pot_Bag_Pink_Dot_Print',
      category: 'Home Goods',
      image: '/images/Pot_Pink_Dot_Bag.jpg',
      price: 10,
      countInStock: 1,
      rating: 0,
      numReviews: 0,
      description: 'Pink Dot print potato bag (includes instructions)',
    },
    {
      _id: '16',
      name: 'Potato Bag Red Basket Weave Print',
      slug: 'Pot_Bag_Red_BasketW_Print',
      category: 'Home Goods',
      image: '/images/Pot_Red_Bag.jpg',
      price: 10,
      countInStock: 1,
      rating: 0,
      numReviews: 0,
      description: 'Red basket weave print potato bag (includes instructions)',
    },
    {
      _id: '17',
      name: 'Potato Bag White Floral Print',
      slug: 'Pot_Bag_White_Floral_Print',
      category: 'Home Goods',
      image: '/images/Pot_White_Floral_Bag.jpg',
      price: 10,
      countInStock: 1,
      rating: 0,
      numReviews: 0,
      description: 'White floral print potato bag (includes instructions)',
    },
    {
      _id: '18',
      name: 'Rainbow DNA Helix Earrings',
      slug: 'Rainbow_DNA_Helix_Ear',
      category: 'Earrings',
      image: '/images/Psych_Ear.jpg',
      price: 6,
      countInStock: 2,
      rating: 0,
      numReviews: 0,
      description: 'Rainbow colored metal DNA helix earrings',
    },
    {
      _id: '19',
      name: 'Rainbow Themed Treble Clef Pendant Necklace',
      slug: 'Rainbow_Treble_Pendant_Neck',
      category: 'Necklaces',
      image: '/images/Rainbow_Treble.jpg',
      price: 8,
      countInStock: 1,
      rating: 0,
      numReviews: 0,
      description: 'Rainbow themed treble clef on silver chain (with extender)',
    },
    {
      _id: '20',
      name: 'White Macrame Keychain',
      slug: 'White_Mac_Key',
      category: 'Keychains',
      image: '/images/Simple_Mac_Key.jpg',
      price: 6,
      countInStock: 1,
      rating: 0,
      numReviews: 0,
      description: 'Simple white macrame keychain',
    },
    {
      _id: '21',
      name: 'Sunflower Drop Earrings',
      slug: 'Sunflower_Drop_Ear',
      category: 'Earrings',
      image: '/images/Sunflower_Ear.jpg',
      price: 7,
      countInStock: 2,
      rating: 0,
      numReviews: 0,
      description:
        'Black beaded sunflower drop earrings (50% of price donated to Ukraine)',
    },
    {
      _id: '22',
      name: 'Glass Beaded Tree of Life Resin Drop Earrings',
      slug: 'Glass_Bead_ToL_Resin_Ear',
      category: 'Earrings',
      image: '/images/Tree_of_Life_Ear.jpg',
      price: 9,
      countInStock: 2,
      rating: 0,
      numReviews: 0,
      description:
        'Glass beaded drop earrings with resin tree of life charm earrings',
    },
    {
      _id: '23',
      name: 'Blue Multi-Print Diagonal Quilted Place Mats (Set of 6)',
      slug: 'Blue_Diag_Quilted_Place_Set',
      category: 'Home Goods',
      image: '/images/Blue_Diagonal_Placemat_Set.jpg',
      price: 35,
      countInStock: 1,
      rating: 0,
      numReviews: 0,
      description:
        'Blue multi-print quilted place mats with diagonal and vertical pattern',
    },
  ],
};

export default data;
